version: "3.8"

services:
  client:
    build:
      context: ../client
      dockerfile: ../docker/Dockerfile.client
    ports:
      - "3000:3000"
      - "24678:24678"
    volumes:
      - ../client:/var/www/html
